### ISSUE TITLE
MetadataKey are strings not ints

### ISSUE THREAD

**Issue by bakes82** [jensenkd/plex-api#11]
When trying to get children data the method wants an int, but the value is a string,  Im using the RatingKey.  Key is also a string, but doesnt look like the real key.

var metadatas = plexApi.GetChildrenMetadata(string authToken, string plexServerHost, int metadataKey).Result;

![image](https://user-images.githubusercontent.com/3197191/83805361-bc63c780-a67d-11ea-8b83-46c147c13247.png)

**Comment by jensenkd** [comment]
RatingKey is what you'll want.  You'll have to convert the string to an int.  There is an open issue on cleaning up types: https://github.com/jensenkd/plex-api/issues/5
