### ISSUE TITLE
Add a method to find the servers that are online

### ISSUE THREAD

**Issue by seertenedos** [jensenkd/plex-api#13]
It would be great if there was a plexApi.GetServers(user.AuthenticationToken) method or something that used it result that filtered the list to just servers currently online.

**Comment by jfranpino** [comment]
I think the same, it would be great

**Comment by jensenkd** [comment]
Does anyone know of a flag that exists to show the server is online or not.  I'm not seeing anything, and we most likely have to attempt to connect.

**Comment by jensenkd** [comment]
This is fixed in 2.0.  

account.ServerSummaries() will return ServerSummary objects that show all servers tied to account regardless of active status.  

account.Servers() will only pull active servers.
