### ISSUE TITLE
Integer overflow exception within automapper, on property MovieLibrary.ContentChangedAt

### ISSUE THREAD

**Issue by Popsikill** [jensenkd/plex-api#25]
Updated the code locally with `long` and seemed to work as expected.
Link to change - https://github.com/jensenkd/plex-api/blob/fbf6fda5445fcb9d22d6844bbb52192c294cd3ed/Source/Plex.Api/ApiModels/Libraries/MovieLibrary.cs#L47

Value coming from Plex library: `8386072425077913282`

Cheers!

**Comment by jensenkd** [comment]
Thanks @Popsikill , I will have to go through again and make sure I didn't miss any.
