### ISSUE TITLE
Signing in with Token Throws Exception

### ISSUE THREAD

**Issue by elzik** [jensenkd/plex-api#31]
When signing in with a token:

```
var plexFactory = serviceProvider.GetService<IPlexFactory>();
var account = plexFactory.GetPlexAccount(token);
```

I see an exception thrown, see below. I am running `2.0.0-preview024` and I see that a similar bug had been fixed in that version. I also downgraded to `2.0.0-preview023` but had the same problem. I am running plex v1.23.3.4707 on Linux.

  | Name | Value | Type
-- | -- | -- | --
◢ | $exception | {"Error mapping types.\r\n\r\nMapping types:\r\nPlexAccount -> PlexAccount\r\nPlex.ServerApi.PlexModels.Account.PlexAccount -> Plex.Library.ApiModels.Accounts.PlexAccount\r\n\r\nType Map configuration:\r\nPlexAccount -> PlexAccount\r\nPlex.ServerApi.PlexModels.Account.PlexAccount -> Plex.Library.ApiModels.Accounts.PlexAccount\r\n\r\nDestination Member:\r\nRememberExpiresAt\r\n"} | AutoMapper.AutoMapperMappingException
  | ▶ Data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
  | HResult | -2146233088 | int
  | HelpLink | null | string
  | ▶ InnerException | {"07/17/2021 14:04:38 is not a valid value for DateTime."} | System.Exception {System.FormatException}
  | ▶ MemberMap | "RememberExpiresAt" | AutoMapper.IMemberMap {AutoMapper.PropertyMap}
  | Message | "Error mapping types.\r\n\r\nMapping types:\r\nPlexAccount -> PlexAccount\r\nPlex.ServerApi.PlexModels.Account.PlexAccount -> Plex.Library.ApiModels.Accounts.PlexAccount\r\n\r\nType Map configuration:\r\nPlexAccount -> PlexAccount\r\nPlex.ServerApi.PlexModels.Account.PlexAccount -> Plex.Library.ApiModels.Accounts.PlexAccount\r\n\r\nDestination Member:\r\nRememberExpiresAt\r\n" | string
  | Source | "AutoMapper" | string
  | StackTrace | "   at lambda_method1(Closure , PlexAccount , PlexAccount , ResolutionContext )\r\n   at Plex.Library.ApiModels.Accounts.PlexAccount..ctor(IPlexAccountClient plexAccountClient, IPlexServerClient plexServerClient, IPlexLibraryClient plexLibraryClient, String authToken)\r\n   at Plex.Library.Factories.PlexFactory.GetPlexAccount(String authToken)\r\n   at TestPlex.Program.Main(String[] args) in C:\\Users\\justin.elzik\\Dropbox\\Source\\Plex\\TestPlex\\TestPlex\\Program.cs:line 46" | string
  | ▶ TargetSite | {TDestination MapCore[TSource,TDestination](TSource, TDestination, AutoMapper.ResolutionContext, System.Type, System.Type, AutoMapper.IMemberMap)} | System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
  | ▶ TypeMap | "PlexAccount" -> "PlexAccount" | AutoMapper.TypeMap
  | ▶ Types | "PlexAccount", "PlexAccount" | AutoMapper.TypePair?

</body>
</HTML>

**Comment by elzik** [comment]
Changing my regional format from "English (United Kingdom)" to "English (United States)" temporarily works around the problem. It looks to be a localisation issue.

**Comment by mattheys** [comment]
> 
> 
> Changing my regional format from "English (United Kingdom)" to "English (United States)" temporarily works around the problem. It looks to be a localisation issue.

How did you do this, was it a browser setting or did you do it in your code?

**Comment by jensenkd** [comment]
Try Version 2.0.0-preview27.  I'm now returning UTC Datetimes so it should not care about localization.
