### ISSUE TITLE
Plex.Api.sln missing projects

### ISSUE THREAD

**Issue by cruce** [jensenkd/plex-api#32]
**Describe the bug**
Not necessarily a bug, but missing folders and files from project download. After I Git Clone and open the Plex.Api.sln in Visual Studio 2019, I get the following errors and warnings.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1104	Unable to find project 'C:\GitProjects\plex-api\Source\Plex.Api\Plex.Api.csproj'. Check that the project reference is valid and that the project file exists.	Plex.Library.Test	C:\GitProjects\plex-api\Tests\Plex.Library.Test\Plex.Library.Test.csproj	1
Error	NU1104	Unable to find project 'C:\GitProjects\plex-api\Source\Plex.Api\Plex.Api.csproj'. Check that the project reference is valid and that the project file exists.	Plex.ServerApi.Test	C:\GitProjects\plex-api\Tests\Plex.ServerApi.Test\Plex.ServerApi.Test.csproj	1	
Warning		The referenced project '..\..\Source\Plex.Api\Plex.Api.csproj' does not exist.	Plex.Library.Test	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	1966	
Warning		The referenced project '..\..\Source\Plex.Api\Plex.Api.csproj' does not exist.	Plex.ServerApi.Test	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	1966	
```

There doesn't appear to be a Plex.Api folder in the Source folder.

**To Reproduce**
1. Clone the project to your computer, https://github.com/jensenkd/plex-api.git
2. Go into the resulting plex-api folder.
3. Double-click on the Plex.Api.sln solution file to open it in Visual Studio. In my case, Visual Studio 2019
4. See error and warning messages in Output

**Expected behavior**
I expected there would be no missing folders and files or information in the README.md that would explain the need to download additional files.

**Screenshots**
Not necessary.

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Visual Studio 2019
 - .NET SDK 5.0.301
 - .NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
Basically, I am trying to follow the README.md for my own project and getting lots of error messages with the following piece of code:

```
// Create Client Options
    var apiOptions = new ClientOptions
    {
        Product = "API_UnitTests",
        DeviceName = "API_UnitTests",
        ClientId = "MyClientId",
        Platform = "Web",
        Version = "v1"
    };

    // Setup Dependency Injection
    var services = new ServiceCollection();
    services.AddSingleton(apiOptions);
    services.AddTransient<IPlexServerClient, PlexServerClient>();
    services.AddTransient<IPlexAccountClient, PlexAccountClient>();
    services.AddTransient<IPlexLibraryClient, PlexLibraryClient>();
    services.AddTransient<IApiService, ApiService>();
    services.AddTransient<IPlexFactory, PlexFactory>();
    services.AddTransient<IPlexRequestsHttpClient, PlexRequestsHttpClient>();
    
    this.ServiceProvider = services.BuildServiceProvider();
```

I have found that I can resolve the error messages for "The type or namespace 'xxxxxxx' could not be found..." for the following items by adding the code below.

- ClientOptions
- ServiceCollection
- PlexAccount

```
using Microsoft.Extensions.DependencyInjection;
using Plex.Api;
using Plex.Api.Models;
```

However, I am still new to C# and Microsoft's Dependency Injection and not sure how to resolve the other missing namespaces for ServiceProvider and all of the IPlex.... items.

So, I was hoping to open the Plex.Api.sln solution and look at the different projects to find out what I am missing. Honestly, it would be great and save me lots of hours if the required information was in the README.md file and not just assume everyone knows what to include to make the code work.

**Comment by jensenkd** [comment]
per the global.json, sdk version 5.0.400

 "version": "5.0.400",
