### ISSUE TITLE
System.FormatException: 09/20/2021 13:04:37 is not a valid value for DateTime.

### ISSUE THREAD

**Issue by mattheys** [jensenkd/plex-api#35]
**Describe the bug**
I'm getting the same thing as #27 when doing `server.Libraries()` with 2.0.0-preview025 from Nuget

**To Reproduce**
Steps to reproduce the behavior: https://github.com/jensenkd/plex-api/blob/master/README.md#library-documentation
1. I guess use a non US datetime location (UK)?
2. plexAccount = plexFactory.GetPlexAccount(PlexKey);
3. plexServers = await plexAccount.Servers();
4. plexLibraries = await plexServers[0].Libraries();

**Expected behavior**
Returns a list of Libraries for the server

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser FireFox
 - Version 2.0.0-preview25

**Comment by jensenkd** [comment]
Try Version 2.0.0-preview26. I am now using UTC dates instead of trying to convert to localized timezone.

**Comment by mattheys** [comment]
Sorry for taking a while to get back to you, I updated to 2.0.5-preview001 and it's working now, I had a work around in place so hadn't updated.
