### ISSUE TITLE
GetChildrenMetadataAsync returns an empty MediaContainer class

### ISSUE THREAD

**Issue by mattheys** [jensenkd/plex-api#36]
**To Reproduce**
```
 //SelectedPlexLibrary.PlexServer is Plex.Library.ApiModels.Servers.Server

    async Task Card(Metadata item)
    {
        if (item.Type == "show")
        {
            var seasons = await plexServerClient.GetChildrenMetadataAsync(SelectedPlexLibrary.PlexServer.AccessToken,SelectedPlexLibrary.PlexServer.Uri.ToString(), int.Parse(item.RatingKey));
        }
    }
```
**Expected behavior**
To return the correct MediaContainer information

**Additional context**
I have run the query manually through Postman an as far as I can see it should return the same MediaContainer as other calls. 

While I'm at it, is it possible to get a method on Plex.Library.ApiModels.Libraries.ShowLibrary to be able to get Seasons/Episodes of a particular show or season using the rating key?

Not that I'm ungrateful mind you this has saved me hours of work already.

**Comment by jensenkd** [comment]
I was able to replicate this and i'm working on it.

**Comment by jensenkd** [comment]
try v2.0.5-preview002 on nuget (pre-release).  I've added separate task for new method.

**Comment by jensenkd** [comment]
see #37
