### ISSUE TITLE
Add ability to manage collections

### ISSUE THREAD

**Issue by jensenkd** [jensenkd/plex-api#4]
Add ability to Add/Remove/Update/Create and list collections

**Comment by willkara** [comment]
Awesome! Let me know how I can help :)

**Comment by jensenkd** [comment]
> Awesome! Let me know how I can help :)

I've implemented the use cases I need around collections.  Can you let me know your use cases to make sure their covered?

**Comment by willkara** [comment]
*	Get a list of current collections

*	See the media in those collections

*	Create a new collection

*	Add media to that collection

*	Delete a collection

**Comment by jensenkd** [comment]
OK I have all those covered.

I don't think there is a way to just 'Create a new Collection' in Plex.  It appears you create it by adding it to an existing movie? https://support.plex.tv/articles/201273953-collections/

I also can't find a way to add media to a collection.  There must be a way vs having to add the collection to each media item separately but I can't find it yet.

**Comment by willkara** [comment]
So it looks like you’d just need to add the respective collections tag you want to the media you want.

 

I’ll try and explore the existing API and try some GoogleFU to see if I find anything.

 

Nicejob!

**Comment by jensenkd** [comment]
Hopefully this covers it.  Let me know if there are any issues.
