### ISSUE TITLE
OAuth not working?

### ISSUE THREAD

**Issue by mattheys** [jensenkd/plex-api#40]
I'm not sure if this is me but since the Plex auth outage on the 27th I've not managed to sign in with OAuth again. https://status.plex.tv/

I signed out of Tautulli and back in and that worked, except they are not using the forwardUrl method.

**To Reproduce**
```
    [Route("api/[controller]")]
    public class PlexLoginController : Controller
    {
        private readonly OAuthService _oAuthService;
        private readonly IPlexAccountClient _plexClient;

        public PlexLoginController(OAuthService oAuthService, IPlexAccountClient plexClient)
        {
            _oAuthService = oAuthService;
            _plexClient = plexClient;
        }

        [HttpGet]
        public async Task<IActionResult> IndexAsync()
        {
            var returnPath = Request.Scheme + "://" + Request.Host + Request.Path + "/PlexReturn";
            var oauthUrl = await _plexClient.CreateOAuthPinAsync(returnPath);
            _oAuthService.OAuthID = oauthUrl.Id;
            return Redirect(oauthUrl.Url);
        }

        [HttpGet]
        [Route("PlexReturn")]
        public async Task<IActionResult> PlexReturn()
        {
            var oauthId = _oAuthService.OAuthID.ToString();
            var oAuthPin = await _plexClient.GetAuthTokenFromOAuthPinAsync(oauthId);

            if (string.IsNullOrEmpty(oAuthPin.AuthToken))
                throw new Exception("Plex auth failed.");

            _oAuthService.PlexKey = oAuthPin.AuthToken;
            await _oAuthService.Login(oAuthPin.AuthToken);
            return Content(@"<script>window.close();</script>", "text/html");
        }
    }
```
The Plex login window says "We were unable to complete this request."
![image](https://user-images.githubusercontent.com/10292436/135438667-aa64b8f3-5437-4893-8510-539ec90de507.png)

**Expected behavior**
To obtain a Plex Authentication Token

**Desktop (please complete the following information):**
 - OS: Windows
 - Blazor Server 
 - Visual Studio 2019 (16.11.3)
 - Plex.Api 2.0.5-preview006

**Comment by mattheys** [comment]
Been trying to do this manually in postman and was hitting the same issues, when I added `strong=true` to the POST body to https://plex.tv/api/v2/pins it worked in postman. 

I tried to clone your repo and add your projects to my solution to see if I could make that tweak but I couldn't get it to work that way.

**Comment by jensenkd** [comment]
They may have changed something in the api.  I'll take a look

**Comment by jensenkd** [comment]
this is working for me.  Do you have your code posted somewhere?  I could try it on my server.

**Comment by jensenkd** [comment]
OK I've pulled in your code into the project /Samples.  I think i've fixed the issue for opening up the source code in Visual Studio on Windows if you want to pull down the code and try opening it again.

I'll debug this next and check into the strong=true addition.

Thanks!
