### ISSUE TITLE
Not able to access LibraryBase.RecentlyAdded() method

### ISSUE THREAD

**Issue by CorruptComputer** [jensenkd/plex-api#52]
# **Describe the bug**
Following the [documentation in the README for Libraries](https://github.com/jensenkd/plex-api#library-documentation) will lead you to the following error.
```
'LibraryBase.RecentlyAdded(SearchType, int, int)' is inaccessible due to its protection level
```

Was this API changed since this documentation was written?

# **To Reproduce**
Here is an excerpt from my code, this should be cut down enough to show the issue without being too much code I think.
```csharp
internal async Task Test()
{
    // Login to Plex
    PlexAccount account = _plexFactory.GetPlexAccount(
        "YOUR TOKEN HERE"
    );

    // Only needed if you have more than 1 server owned
    string serverNameToMonitor = "SERVER NAME HERE";

    // Select the available server to check
    List<Server> ownedServers = (await account.Servers()).Where(s => s.Owned == 1).ToList();
    Server monitoredServer = ownedServers.Count switch
    {
        > 1 => ownedServers.First(s => s.FriendlyName == serverNameToMonitor),
        1 => ownedServers.First(),
        _ => throw new UnrecoverableException("You have no owned servers on your Plex account!")
    };

    // Make sure the data we have is up to date
    await monitoredServer.RefreshSync();

    // Check the recently added media in the library
    List<LibraryBase> libraries = await monitoredServer.Libraries();
    foreach (LibraryBase library in libraries)
    {
        MediaContainer recentlyAdded = await library.RecentlyAdded();
    }
}
```

# **Expected behavior**
I should be able to check the Recently Added for libraries on my server.

# **Screenshots**
![image](https://user-images.githubusercontent.com/5573038/154962562-0e259597-2425-40d7-8746-cfbf33297770.png)

# **Desktop (please complete the following information):**
 - **OS: [e.g. iOS]:** Windows 10
 - **Browser [e.g. chrome, safari]:** Not sure how browser is relevant for this library, but the editor I'm using is Visual Studio 2022.
 - **Version [e.g. 22]:** Nuget package Plex.Api version 2.0.4

# **Additional context**
If I'm really not sure if I'm doing something wrong here or if the documentation is wrong, but either way I thought of opening an issue to check on this. Thank you in advance for your time!

**Comment by Pouleyy** [comment]
Hello ! 
I've come to the same issue as yours and it appears that `LibraryBase` object doesn't have access to `RecentlyAdded` method.
In order to have the list you must do something like
`var showLibrary = library as ShowLibrary` or `var movieLibrary = library as MovieLibrary` based on `LibraryBase.Type` and with the cast you should be able to access to `RecentlyAdded` method
Hope it'll help you !
