### ISSUE TITLE
GetServers Not Returning All Servers

### ISSUE THREAD

**Issue by bbakermmc** [jensenkd/plex-api#7]
It looks like the GetServers isnt working correctly.  I can only see 1 server (my local).  But I have multiple.

**Comment by bbakermmc** [comment]
Im doing a blazor project, and Im just awaiting the call, I get the first record,  if I use the .Results the project just hangs trying to pull records.
```c#
@page "/plex"
@using Microsoft.AspNetCore.Http
@using PlexApps.Plex
@using global::Plex.Api
@using global::Plex.Api.Models.Server

@inject PlexOAuthClient PlexOAuthClient
@inject IHttpContextAccessor HttpContextAccessor
@inject IPlexClient PlexClient

<h1>Plex</h1>

@if (Servers == null)
{
    <p>
        <em>Loading...</em>
    </p>
}
else
{
    <table class="table">
        <thead>
        <tr>
            <th>Name</th>
            <th>Version</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var server in Servers)
        {
            <tr>
                <td>@server.Name</td>
                <td>@server.Version</td>
                @{
                    string link = $"/libraries/{server.MachineIdentifier}"; 
            } 
                <td><NavLink href="@link">Set Server</NavLink></td>
            </tr>
        }
        </tbody>
    </table>
}


@code {
    private List<Server> Servers { get; set; }

    protected override async Task OnInitializedAsync()
    {
        var plexKey = HttpContextAccessor.HttpContext.Session.GetString("PlexKey");
        Servers = await PlexClient.GetServers(plexKey);
    }
}
```

**Comment by jensenkd** [comment]
I haven't tried Blazer yet, but I'll see if I can scaffold a quick project to test it.

If you use the access token for a single server, it will return only that server.  You need to use the access token from your plex login (which is different).

**Comment by bbakermmc** [comment]
If I use the test project and just pass over my token. Still only 1 result.  Have you tried with multiple?  It seems like most of your endpoints don’t return multiple things.

**Comment by bbakermmc** [comment]
Here is the server calls from the trakt to plex solution and it works fine.


```C#
public async Task<Server[]> GetServers()
        {
            var servers = new List<Server>();
            using (var request = new HttpRequestMessage(HttpMethod.Get, "https://plex.tv/api/resources"))
            {
                var resp = await _httpClient.SendAsync(request);
                var respStr = await resp.Content.ReadAsStringAsync();
                var xmlDoc = new XmlDocument();
                xmlDoc.LoadXml(respStr);
                var container = xmlDoc.ChildNodes.OfType<XmlNode>().FirstOrDefault(x => x.Name == "MediaContainer");
                if (container == null)
                    return new Server[0];
                foreach (var serverNode in container.ChildNodes.OfType<XmlNode>().Where(x => x.Attributes["product"].Value == "Plex Media Server" && x.ChildNodes.OfType<XmlNode>().Any(y => y.Attributes["local"].Value == "0")))
                {
                    servers.Add(new Server
                    {
                        Name = serverNode.Attributes["name"].Value,
                        Id = serverNode.Attributes["clientIdentifier"].Value,
                        Url = serverNode.ChildNodes.OfType<XmlNode>().First(x => x.Attributes["local"].Value == "0").Attributes["uri"].Value
                    });
                }

                return servers.ToArray();
            }
```

**Comment by bbakermmc** [comment]
@jensenkd Just to confirm.  Using the API-Test Test_SignIn, I take the access token from the User object on that test, and then use it in the Test_Get_Server and I only get 1 server.  Iver never seen different types of access keys before for Plex.  All the python scripts work the same.

**Comment by jensenkd** [comment]
take a look at the test Test_Get_Account()

This will give you a plex account Authentication Token.  I believe Signin is for manipulating your account on Plex.tv.

**Comment by bbakermmc** [comment]
Like I said, pretty sure plex only has 1 key.  There is no diff.

I have a key using my old oauth code, that key is saved into session as you can see, then I call your method to get the account, I take that key pass it to the servers as you can see the key the same even after I call get account, and servers still only returns 1.

![image](https://user-images.githubusercontent.com/30090055/82829960-85720280-9e82-11ea-9900-db845e24b45f.png)

**Comment by jensenkd** [comment]
Thats very strange.. I get multiple servers:
![image](https://user-images.githubusercontent.com/170765/82830476-763b8680-9e7b-11ea-99f3-cf285b2918e9.png)

**Comment by jensenkd** [comment]
It's weird..there is no scenario where I don't get 2 servers. 

I mean the code is very simple..it's really just returning the xml response from this:
https://plex.tv/pms/servers.xml?X-Plex-Token=YOUR_TOKEN_HERE

If you put your token in that link, you're getting both servers?

**Comment by bbakermmc** [comment]
I’ll try tonight but pretty sure I only got one.

**Comment by bbakermmc** [comment]
The server that shows up is my locally hosted sever but not the one remotely hosted

**Comment by bbakermmc** [comment]
Confirming that servers.xml does now show me two servers.
![image](https://user-images.githubusercontent.com/30090055/82847261-27addc80-9ebb-11ea-993d-0a7d04a4cdef.png)

**Comment by bbakermmc** [comment]
Looks like its pulling it from
here: https://plex.tv/api/v2/resources?includeHttps=1&includeRelay=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.34.2&X-Plex-Client-Identifier=i8r7syej5lhb5gxnwmq1vzhv&X-Plex-Platform=Firefox&X-Plex-Platform-Version=76.0&X-Plex-Sync-Version=2&X-Plex-Features=external-media%2Cindirect-media&X-Plex-Model=hosted&X-Plex-Device=Windows&X-Plex-Device-Name=Firefox&X-Plex-Device-Screen-Resolution=1920x771%2C1920x1200&X-Plex-Token=TOKENME&X-Plex-Language=en

or 

https://plex.tv/devices.xml?X-Plex-Product=Plex%20Web&X-Plex-Version=4.34.2&X-Plex-Client-Identifier=i8r7syej5lhb5gxnwmq1vzhv&X-Plex-Platform=Firefox&X-Plex-Platform-Version=76.0&X-Plex-Sync-Version=2&X-Plex-Features=external-media%2Cindirect-media&X-Plex-Model=hosted&X-Plex-Device=Windows&X-Plex-Device-Name=Firefox&X-Plex-Device-Screen-Resolution=1920x771%2C1920x1200&X-Plex-Token=TOKENME&X-Plex-Language=en

**Comment by bbakermmc** [comment]
@jensenkd Can you make a devices endpoint, I can use that instead.  I'm just trying to use this api though, so as soon as you can give me a list of servers I can get further with what Im trying to do :)

**Comment by jensenkd** [comment]
```
[TestMethod]
public void Test_Get_Resources()
{
      var plexApi = ServiceProvider.GetService<IPlexClient>();
      var authKey = Configuration.GetValue<string>("Plex:AuthenticationKey");
      var resources = plexApi.GetResources(authKey).Result;
      Assert.IsNotNull(resources);
}
```

**Comment by bbakermmc** [comment]
@jensenkd Looks good for me.  This is what I did:

On my prev page, I have user select the server, pass that clientId over, then re lookup the stuff.  But you need to pull the URI from the connections Id assume you want HTTPS and non locals ;)  You can then pass that URI to the other methods that take the URL and it works perfect.  Ill let you know if I need something else lol.  Some of the properties could be changed from string to bool if you looked at the data sets, basically all the 1/0 options but thats minor.

```c#
 var plexKey = HttpContextAccessor.HttpContext.Session.GetString("PlexKey");
        var servers = await PlexClient.GetResources(plexKey);
        var serverUrl = ((servers.SingleOrDefault(x => x.ClientIdentifier == Server)?.Connections) ?? throw new InvalidOperationException()).FirstOrDefault(y => y.Protocol == "https" && y.Local == "0")?.Uri;
        Libs = await PlexClient.GetLibraries(plexKey, serverUrl);
```

**Comment by jensenkd** [comment]
@bbakermmc looks good.  Yes I have a task to look at all the types. 
[https://github.com/jensenkd/plex-api/issues/5](url)

The Plex Api is crap and is inconsistent in their types across different endpoints.  We're probably safe with the Resource model since they are not returned from any other endpoints that I can tell.
