### ISSUE TITLE
Scrobble/Unscrobble

### ISSUE THREAD

**Issue by bbakermmc** [jensenkd/plex-api#9]
Mark items as watched
```c#

public async Task Scrobble(string ratingKey)
        {
            using (var request = new HttpRequestMessage(HttpMethod.Get,
                "/:/scrobble?identifier=com.plexapp.plugins.library&key=" + ratingKey))
            {
                var resp = await _httpClient.SendAsync(request);
                var respStr = await resp.Content.ReadAsStringAsync();
            }
        }

public async Task Unscrobble(string ratingKey)
        {
            using (var request = new HttpRequestMessage(HttpMethod.Get,
                "/:/unscrobble?identifier=com.plexapp.plugins.library&key=" + ratingKey))
            {
                var resp = await _httpClient.SendAsync(request);
                var respStr = await resp.Content.ReadAsStringAsync();
            }
        }
```

**Comment by jensenkd** [comment]
@bbakermmc is the only way to determine the 'Played' flag.. if (media.PlayCount > 0)?  Is there some other flag?  Building out unit tests.

**Comment by bbakermmc** [comment]
Last Watched Time?  Not sure if you can have a Play >0 and no last watched.  I just use the Count > 0,  But if you are making edits and want to make a bool HasBeenWatched that checks either or both Im all for it :P

**Comment by jensenkd** [comment]
@bbakermmc yeah..thats what I was contemplating.  For now, I'll just add the methods and determine whether to add that flag later.

**Comment by bbakermmc** [comment]
Its easy enough to figure out :)
![unknown](https://user-images.githubusercontent.com/30090055/83039812-951d5280-a00c-11ea-8f87-821d664a0acd.png)

**Comment by jensenkd** [comment]
@bbakermmc v1.0.95

That app looks awesome.  You're using it to sync multiple plex instances with Trakt?

**Comment by bbakermmc** [comment]
@jensenkd One feature set is to push/pull to trakt, yes.  You could login to server 1, push all to trakt, make a new server, login to that pull all from trakt.

That UI was mainly used for me to make sure the matching of the trakt to plex meta is correct :)  Plus getting to know Blazor.  Now I can add individual buttons to test the scrobbles and do one ups, then I can make the method to do it all :P

Ill prob steal your post thing :P

**Comment by jensenkd** [comment]
@bbakermmc very cool!
